survey = [{'question': 'Where do you live?',
  'answers': [{'answer': 'Arroyo Grande',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Atascadero',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Avila Beach',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Bradley',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Buellton',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Cambria',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Cayucos',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Creston',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Grover Beach',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Guadalupe',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Harmony',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Heritage Ranch',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Lompoc',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Los Osos',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Morro Bay',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Nipomo',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Oceano',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Orcutt',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Paso Robles',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Pismo Beach',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'San Luis Obispo',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'San Miguel',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'San Simeon',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Santa Margarita',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Santa Maria',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Shandon',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Templeton',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Other Santa Barbara County',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 1,
    'tutor': 1,
    'career mentor': 1,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': 'Outside the Central Coast',
    'foster parent': 1,
    'respite/tcp': 1,
    'host home': 1,
    'mentor': 1,
    'tutor': 1,
    'career mentor': 1,
    'volunteer': 3,
    'donate/support': 6}]},
 {'question': 'What is your household make up?',
  'answers': [{'answer': '1) Single no kids',
    'foster parent': -100,
    'respite/tcp': -100,
    'host home': -100,
    'mentor': -100,
    'tutor': -100,
    'career mentor': -100,
    'volunteer': -100,
    'donate/support': -100},
   {'answer': '2) Single w/ kids',
    'foster parent': -100,
    'respite/tcp': -100,
    'host home': -100,
    'mentor': -100,
    'tutor': -100,
    'career mentor': -100,
    'volunteer': -100,
    'donate/support': -100},
   {'answer': '3) Spouse/partner no kids',
    'foster parent': -100,
    'respite/tcp': -100,
    'host home': -100,
    'mentor': -100,
    'tutor': -100,
    'career mentor': -100,
    'volunteer': -100,
    'donate/support': -100},
   {'answer': '4) Spouse/partner w/ kids',
    'foster parent': -100,
    'respite/tcp': -100,
    'host home': -100,
    'mentor': -100,
    'tutor': -100,
    'career mentor': -100,
    'volunteer': -100,
    'donate/support': -100}]},
 {'question': 'How would you describe your work life?',
  'answers': [{'answer': '1) Work full-time away from home',
    'foster parent': 5,
    'respite/tcp': 4,
    'host home': 5,
    'mentor': 4,
    'tutor': 2,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': '2) Work full-time from home',
    'foster parent': 6,
    'respite/tcp': 5,
    'host home': 6,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 5,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': '3) Work full-time but have flexibility',
    'foster parent': 5,
    'respite/tcp': 4,
    'host home': 5,
    'mentor': 8,
    'tutor': 8,
    'career mentor': 8,
    'volunteer': 7,
    'donate/support': 4},
   {'answer': '4) Am a stay-at-home parent',
    'foster parent': 7,
    'respite/tcp': 4,
    'host home': 7,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 8,
    'donate/support': 4},
   {'answer': '5) Work part-time',
    'foster parent': 6,
    'respite/tcp': 4,
    'host home': 6,
    'mentor': 5,
    'tutor': 8,
    'career mentor': 8,
    'volunteer': 7,
    'donate/support': 4},
   {'answer': '6a) I am financially stable',
    'parent': '6) Not currently working',
    'foster parent': 7,
    'respite/tcp': 4,
    'host home': 7,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 6,
    'donate/support': 9},
   {'answer': '6b) I am currently looking for employment',
   'parent': '6) Not currently working',
    'foster parent': 1,
    'respite/tcp': 1,
    'host home': 1,
    'mentor': 2,
    'tutor': 4,
    'career mentor': 2,
    'volunteer': 6,
    'donate/support': 3},
   {'answer': '7) Am retired',
    'foster parent': 7,
    'respite/tcp': 4,
    'host home': 7,
    'mentor': 5,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 7,
    'donate/support': 4}]},
{'question': 'How would you describe your spouse\'s work life?',
 'answers': [{'answer': '1) Work full-time away from home',
   'foster parent': 5,
   'respite/tcp': 4,
   'host home': 5,
   'mentor': 4,
   'tutor': 2,
   'career mentor': 4,
   'volunteer': 4,
   'donate/support': 4},
  {'answer': '2) Work full-time from home',
   'foster parent': 6,
   'respite/tcp': 5,
   'host home': 6,
   'mentor': 4,
   'tutor': 4,
   'career mentor': 5,
   'volunteer': 4,
   'donate/support': 4},
  {'answer': '3) Work full-time but have flexibility',
   'foster parent': 5,
   'respite/tcp': 4,
   'host home': 5,
   'mentor': 8,
   'tutor': 8,
   'career mentor': 8,
   'volunteer': 7,
   'donate/support': 4},
  {'answer': '4) Am a stay-at-home parent',
   'foster parent': 7,
   'respite/tcp': 4,
   'host home': 7,
   'mentor': 4,
   'tutor': 4,
   'career mentor': 4,
   'volunteer': 8,
   'donate/support': 4},
  {'answer': '5) Work part-time',
   'foster parent': 6,
   'respite/tcp': 4,
   'host home': 6,
   'mentor': 5,
   'tutor': 8,
   'career mentor': 8,
   'volunteer': 7,
   'donate/support': 4},
  {'answer': '6a) My spouse is financially stable',
   'parent': '6) Not currently working',
   'foster parent': 7,
   'respite/tcp': 4,
   'host home': 7,
   'mentor': 4,
   'tutor': 4,
   'career mentor': 4,
   'volunteer': 6,
   'donate/support': 9},
  {'answer': '6b) My spouse is currently looking for employment',
  'parent': '6) Not currently working',
   'foster parent': 1,
   'respite/tcp': 1,
   'host home': 1,
   'mentor': 2,
   'tutor': 4,
   'career mentor': 2,
   'volunteer': 6,
   'donate/support': 3},
  {'answer': '7) Am retired',
   'foster parent': 7,
   'respite/tcp': 4,
   'host home': 7,
   'mentor': 5,
   'tutor': 4,
   'career mentor': 4,
   'volunteer': 7,
   'donate/support': 4},
   {'answer': '8) Not applicable. I do not have a spouse',
    'foster parent': 0,
    'respite/tcp': 0,
    'host home': 0,
    'mentor': 0,
    'tutor': 0,
    'career mentor': 0,
    'volunteer': 0,
    'donate/support': 0}]},       
 {'question': 'How do you see yourself becoming involved with foster care?',
  'answers': [{'answer': '1) I want to provide a foster child/youth with a home',
    'foster parent': 8,
    'respite/tcp': 6,
    'host home': 6,
    'mentor': 4,
    'tutor': 2,
    'career mentor': 2,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': "2) I want to be involved in a foster child/youth's life",
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 8,
    'tutor': 8,
    'career mentor': 8,
    'volunteer': 5,
    'donate/support': 5},
   {'answer': '3) I want to support foster parents and foster children as needed',
    'foster parent': 6,
    'respite/tcp': 8,
    'host home': 8,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': "4) I know I want to be involved, but don't know how",
    'foster parent': 3,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 3,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 6,
    'donate/support': 4},
   {'answer': '5) I just want to support the agency',
    'foster parent': 3,
    'respite/tcp': 2,
    'host home': 2,
    'mentor': 2,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 7,
    'donate/support': 9}]},
 {'question': 'How much time do you want to invest?',
  'answers': [{'answer': '1) Full Time',
    'foster parent': 7,
    'respite/tcp': 4,
    'host home': 7,
    'mentor': 2,
    'tutor': 3,
    'career mentor': 2,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': '2) Weekly',
    'foster parent': 1,
    'respite/tcp': 5,
    'host home': 1,
    'mentor': 4,
    'tutor': 8,
    'career mentor': 4,
    'volunteer': 8,
    'donate/support': 4},
   {'answer': '3) Monthly',
    'foster parent': 1,
    'respite/tcp': 7,
    'host home': 1,
    'mentor': 8,
    'tutor': 4,
    'career mentor': 8,
    'volunteer': 4,
    'donate/support': 7},
   {'answer': '4) Periodically',
    'foster parent': 1,
    'respite/tcp': 3,
    'host home': 1,
    'mentor': 3,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 5,
    'donate/support': 5}]},
 {'question': 'How much do you know about foster care?',
  'answers': [{'answer': '1) I know a lot about foster care',
    'foster parent': 6,
    'respite/tcp': 6,
    'host home': 6,
    'mentor': 2,
    'tutor': 2,
    'career mentor': 2,
    'volunteer': 2,
    'donate/support': 6},
   {'answer': '2) I want to become involved/know very little',
    'foster parent': 5,
    'respite/tcp': 5,
    'host home': 5,
    'mentor': 4,
    'tutor': 5,
    'career mentor': 5,
    'volunteer': 5,
    'donate/support': 6},
   {'answer': '3) I have no idea what foster care involves',
    'foster parent': 4,
    'respite/tcp': 5,
    'host home': 4,
    'mentor': 5,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4}]},
 {'question': 'What is your current level of interest?',
  'answers': [{'answer': '1) Very interested and want to get started right away',
    'foster parent': 7,
    'respite/tcp': 7,
    'host home': 7,
    'mentor': 7,
    'tutor': 7,
    'career mentor': 7,
    'volunteer': 7,
    'donate/support': 7},
   {'answer': '2) I am interested, but I would like additional information and guidance',
    'foster parent': 6,
    'respite/tcp': 6,
    'host home': 6,
    'mentor': 6,
    'tutor': 6,
    'career mentor': 6,
    'volunteer': 6,
    'donate/support': 6},
   {'answer': '3) Thinking about getting involved in the next 6–9 months',
    'foster parent': 5,
    'respite/tcp': 5,
    'host home': 5,
    'mentor': 5,
    'tutor': 5,
    'career mentor': 5,
    'volunteer': 5,
    'donate/support': 5},
   {'answer': '4) I am just exploring possibilities right now',
    'foster parent': 3,
    'respite/tcp': 2,
    'host home': 4,
    'mentor': 3,
    'tutor': 2,
    'career mentor': 3,
    'volunteer': 4,
    'donate/support': 4}]},
 {'question': 'How do you want to make an impact?',
  'answers': [
   {'answer': '1a) I have an extra bedroom(s)',
    'parent': '1) I want to help foster children/youth recover',
    'foster parent': 7,
    'respite/tcp': 7,
    'host home': 7,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': '1b) I have a spare bed',
   'parent': '1) I want to help foster children/youth recover',
    'foster parent': 6,
    'respite/tcp': 6,
    'host home': 4,
    'mentor': 2,
    'tutor': 2,
    'career mentor': 2,
    'volunteer': 2,
    'donate/support': 4},
   {'answer': '1c) I don’t have extra space in my home, but am moving',
   'parent': '1) I want to help foster children/youth recover',
    'foster parent': 5,
    'respite/tcp': 5,
    'host home': 5,
    'mentor': 3,
    'tutor': 2,
    'career mentor': 2,
    'volunteer': 2,
    'donate/support': 4},
   {'answer': '1d) No Space',
   'parent': '1) I want to help foster children/youth recover',
    'foster parent': 4,
    'respite/tcp': 5,
    'host home': 4,
    'mentor': 5,
    'tutor': 5,
    'career mentor': 5,
    'volunteer': 5,
    'donate/support': 5},
   {'answer': '2) I want to use my life exiperiences to enrich a foster child/youth',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 8,
    'tutor': 8,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': '3) I want to use my professional experience to help',
    'foster parent': 4,
    'respite/tcp': 4,
    'host home': 4,
    'mentor': 5,
    'tutor': 7,
    'career mentor': 8,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': '4) I want to care for foster children/youth but not full time',
    'foster parent': 1,
    'respite/tcp': 6,
    'host home': 4,
    'mentor': 4,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 4,
    'donate/support': 4},
   {'answer': '5) I want to give back to my community in some way',
    'foster parent': 4,
    'respite/tcp': 3,
    'host home': 4,
    'mentor': 5,
    'tutor': 5,
    'career mentor': 5,
    'volunteer': 8,
    'donate/support': 8}]},
 {'question': 'How is your support network?',
  'answers': [{'answer': '1) I have many close friends and family members',
    'foster parent': 7,
    'respite/tcp': 8,
    'host home': 7,
    'mentor': 6,
    'tutor': 6,
    'career mentor': 6,
    'volunteer': 6,
    'donate/support': 4},
   {'answer': '2) I have a few close friends and family members',
    'foster parent': 6,
    'respite/tcp': 6,
    'host home': 6,
    'mentor': 5,
    'tutor': 6,
    'career mentor': 6,
    'volunteer': 6,
    'donate/support': 4},
   {'answer': '3) I have no close friends or family members',
    'foster parent': 3,
    'respite/tcp': 2,
    'host home': 2,
    'mentor': 3,
    'tutor': 3,
    'career mentor': 3,
    'volunteer': 4,
    'donate/support': 4}]},
 {'question': 'What is your current community involvement?',
  'answers': [{'answer': '1) I am regularly involved in social, community, and/or faith organizations',
    'foster parent': 7,
    'respite/tcp': 8,
    'host home': 7,
    'mentor': 6,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 7,
    'donate/support': 4},
   {'answer': '2) I am occasionally involved in social, community, and/or faith organizations',
    'foster parent': 6,
    'respite/tcp': 6,
    'host home': 6,
    'mentor': 5,
    'tutor': 4,
    'career mentor': 4,
    'volunteer': 6,
    'donate/support': 4},
   {'answer': '3) I am never involved in social, community, and/or faith organizations',
    'foster parent': 3,
    'respite/tcp': 2,
    'host home': 2,
    'mentor': 3,
    'tutor': 3,
    'career mentor': 3,
    'volunteer': 4,
    'donate/support': 4}]},
 {'question': 'What are your hobbies and interests?',
  'answers': [{'answer': '1) Faith-based Activities',
    'foster parent': -100,
    'respite/tcp': -100,
    'host home': -100,
    'mentor': -100,
    'tutor': -100,
    'career mentor': -100,
    'volunteer': -100,
    'donate/support': -100},
   {'answer': '2) Traveling',
    'foster parent': -100,
    'respite/tcp': -100,
    'host home': -100,
    'mentor': -100,
    'tutor': -100,
    'career mentor': -100,
    'volunteer': -100,
    'donate/support': -100},
   {'answer': '3) Pets/farm animals',
    'foster parent': -100,
    'respite/tcp': -100,
    'host home': -100,
    'mentor': -100,
    'tutor': -100,
    'career mentor': -100,
    'volunteer': -100,
    'donate/support': -100},
   {'answer': '4) Volunteer/community involvement',
    'foster parent': -100,
    'respite/tcp': -100,
    'host home': -100,
    'mentor': -100,
    'tutor': -100,
    'career mentor': -100,
    'volunteer': -100,
    'donate/support': -100},
   {'answer': '5) Home-centered Activities',
    'foster parent': -100,
    'respite/tcp': -100,
    'host home': -100,
    'mentor': -100,
    'tutor': -100,
    'career mentor': -100,
    'volunteer': -100,
    'donate/support': -100},
   {'answer': '6) Enjoy the outdoors',
    'foster parent': -100,
    'respite/tcp': -100,
    'host home': -100,
    'mentor': -100,
    'tutor': -100,
    'career mentor': -100,
    'volunteer': -100,
    'donate/support': -100},
   {'answer': '7) Parenting/care-giving',
    'foster parent': -100,
    'respite/tcp': -100,
    'host home': -100,
    'mentor': -100,
    'tutor': -100,
    'career mentor': -100,
    'volunteer': -100,
    'donate/support': -100},
   {'answer': '8) Live Entertainment',
    'foster parent': -100,
    'respite/tcp': -100,
    'host home': -100,
    'mentor': -100,
    'tutor': -100,
    'career mentor': -100,
    'volunteer': -100,
    'donate/support': -100},
   {'answer': '9) Electronic Entertainment',
    'foster parent': -100,
    'respite/tcp': -100,
    'host home': -100,
    'mentor': -100,
    'tutor': -100,
    'career mentor': -100,
    'volunteer': -100,
    'donate/support': -100},
   {'answer': '10) Being Physically Active',
    'foster parent': -100,
    'respite/tcp': -100,
    'host home': -100,
    'mentor': -100,
    'tutor': -100,
    'career mentor': -100,
    'volunteer': -100,
    'donate/support': -100},
   {'answer': '11) Enjoying Solitary Activities',
    'foster parent': -100,
    'respite/tcp': -100,
    'host home': -100,
    'mentor': -100,
    'tutor': -100,
    'career mentor': -100,
    'volunteer': -100,
    'donate/support': -100}]}]
